stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "portal_api"
  DOCKER_TAG: "latest"
  DOCKER_IMAGE_MAIL: "sendmail_api"
  DOCKER_TAG_MAIL: "latest"
  DOCKER_IMAGE_MQ: "portalmq_api"
  DOCKER_TAG_MQ: "latest"
  DEPLOY_PATH: "/home/deloy"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - df -h
  script:
    - echo "Bắt đầu build Docker images"
    - docker-compose build
    - echo "Lưu portal_api image"
    - docker save $DOCKER_IMAGE:$DOCKER_TAG -o portal_api.tar
    - echo "Copy portal_api.tar"
    - cp portal_api.tar $DEPLOY_PATH/
    - echo "Lưu sendmail_api image"
    - docker save $DOCKER_IMAGE_MAIL:$DOCKER_TAG_MAIL -o sendmail_api.tar
    - echo "Copy sendmail_api.tar"
    - cp sendmail_api.tar $DEPLOY_PATH/
    - echo "Lưu portalmq_api image"
    - docker save $DOCKER_IMAGE_MQ:$DOCKER_TAG_MAIL -o portalmq_api.tar
    - echo "Copy portalmq_api.tar"
    - cp portalmq_api.tar $DEPLOY_PATH/
  tags:
    - cloud
  only:
    - production
  #artifacts:
  #  paths:
  #    - build.log
  #  expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "Dừng các containers hiện tại"
    - docker-compose down || true
    - echo "Load portal_api image"
    - docker load -i $DEPLOY_PATH/portal_api.tar || { echo "Lỗi khi load portal_api image"; exit 1; }
    - echo "Load sendmail_api image"
    - docker load -i $DEPLOY_PATH/sendmail_api.tar || { echo "Lỗi khi load sendmail_api image"; exit 1; }
    - echo "Load portalmq_api image"
    - docker load -i $DEPLOY_PATH/portalmq_api.tar || { echo "Lỗi khi load portalmq_api image"; exit 1; }
    - echo "Khởi động các containers mới"
    - docker-compose up -d || { echo "Lỗi khi khởi động containers"; exit 1; }
  tags:
    - cloud
  only:
    - production