version: '3.9'

services:
  device.api:
    build:
      context: .
      dockerfile: src/Device.API/Dockerfile
    image: device_api:latest
    ports:
      - "6001:8080"  # Port mapping cho API chính
      - "6041:8081"  # Nếu có một cổng phụ nào khác
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Môi trường phát triển
    #volumes:
    #  - ./data/device:/app/data  # Ví dụ: Gắn volume cho lưu trữ dữ liệu nếu cần thiết
    restart: unless-stopped  # Tự động khởi động lại trừ khi bị tắt
    networks:
      - device-network

# Cấu hình mạng cho các services giao tiếp
networks:
  device-network:
    driver: bridge
